# Generated by Django 4.1.2 on 2022-11-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_doctorsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsmodel',
            name='dep_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.deptmodel'),
        ),
    ]
