# Generated by Django 4.1.2 on 2022-11-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_signupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
